[General]
network = TwoQueues
cpu-time-limit = 5000s
real-time-limit = 5000s
sim-time-limit = 5000s
warmup-period = 400s
repeat = 20

# -------------------------
# Llegadas
# -------------------------
**.source1.p = 0.6
**.source1.q = 0.2   # no se usa, pero obligatorio

**.source2.p = 0.6   # no se usa, pero obligatorio
**.source2.q = 0.2
# -------------------------
# Mantenimiento
# -------------------------
**.serverWithMaintenance.Y = 10
**.serverWithMaintenance.m = 2

# Guardar resultados
# output-scalar-file = results.sca
# output-vector-file = results.vec
# Usa variables para que cada una de las 960 corridas tenga su propio espacio
output-scalar-file = ${resultdir}/${configname}-${iterationvarsf}-#${repetition}.sca
output-vector-file = ${resultdir}/${configname}-${iterationvarsf}-#${repetition}.vec

# delay
**.delay1.vector-recording = true
**.delay2.vector-recording = true

# throughput
**.throughput1.vector-recording = true
**.throughput2.vector-recording = true

# colas
**.queue1.qlen.vector-recording = true
**.queue2.qlen.vector-recording = true


# =====================================================
# EXPERIMENTOS (todas las combinaciones del enunciado)
# =====================================================

[Config Experimentos]
description = "Barrido de parametros"

**.source1.p = ${p=0.6,0.7}
**.source2.q = ${q=0.2,0.3}
**.serverWithMaintenance.Y = ${Y=10,20,30}
**.serverWithMaintenance.m = ${m=2,3,4,5}

